/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#00f5ff',
        'on-surface-variant': '#b9caca',
        'inverse-primary': '#00696e',
        'surface-variant': '#273647',
        'inverse-surface': '#d4e4fa',
        'on-tertiary-container': '#596177',
        'on-tertiary-fixed-variant': '#3f465c',
        'error-container': '#93000a',
        'on-primary': '#003739',
        'tertiary': '#fbf9ff',
        'tertiary-fixed-dim': '#bec6e0',
        'surface-bright': '#2c3a4c',
        'surface-container-low': '#0d1c2d',
        'on-background': '#d4e4fa',
        'surface-container-high': '#1c2b3c',
        'primary': '#e9feff',
        'on-secondary-fixed': '#111c2d',
        'secondary-fixed-dim': '#bcc7de',
        'primary-fixed-dim': '#00dce5',
        'surface-container': '#122131',
        'on-error-container': '#ffdad6',
        'outline-variant': '#3a494a',
        'surface': '#051424',
        'error': '#ffb4ab',
        'on-primary-fixed': '#002021',
        'on-surface': '#d4e4fa',
        'surface-tint': '#00dce5',
        'on-tertiary': '#283044',
        'outline': '#849495',
        'on-secondary-fixed-variant': '#3c475a',
        'secondary': '#bcc7de',
        'inverse-on-surface': '#233143',
        'on-secondary-container': '#aeb9d0',
        'secondary-fixed': '#d8e3fb',
        'background': '#051424',
        'primary-fixed': '#63f7ff',
        'on-primary-container': '#006c71',
        'tertiary-fixed': '#dae2fd',
        'surface-container-highest': '#273647',
        'on-error': '#690005',
        'on-secondary': '#263143',
        'surface-container-lowest': '#010f1f',
        'secondary-container': '#3e495d',
        'on-tertiary-fixed': '#131b2e',
        'tertiary-container': '#d5ddf7',
        'surface-dim': '#051424',
        'on-primary-fixed-variant': '#004f53',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'margin-desktop': '64px',
        'unit': '4px',
        'margin-mobile': '16px',
        'max-width': '1280px',
        'gutter': '24px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'code-block': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'code-block': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-base': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
